### ISSUE TITLE
Can´t download chapters.

### ISSUE THREAD

**Issue by AlexReyCer** [Kogam22/wwcopy#5]
When i try to download chapters i get this error.
`
Traceback (most recent call last):`
     `   File "code.py", line 26, in <module>`
    `synopsis = soup.select('div[class="fr-view"]')[1]`
`IndexError: list index out of range`

From this line of code: 
`synopsis = soup.select('div[class="fr-view"]')[1]`

And if i change the index number to 0 the scripts works fine and lets me chose the range of chapters to download but when its all finished and all the only thing thats saved its the image of the novel.

The novel that i tried to download was Overgeared, i am using Windows 10 and everything is updated according to the guide.

**Comment by 1ycx** [comment]
It works now. Please check the latest version.
